name: Release Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.15.0'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Format code
        run: npm run format
        
      - name: Build extension
        run: npm run build
        
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          body: |
            ## What's Changed
            - Built with Node.js ${{ env.NODE_VERSION }}
            - Extension version: ${{ github.ref_name }}
            
            ## Installation
            1. Download the extension from the release assets
            2. Open Chrome and go to `chrome://extensions/`
            3. Enable "Developer mode"
            4. Click "Load unpacked" and select the downloaded folder
          files: |
            dist/**/*
            README.md
            LICENSE
          draft: false
          prerelease: ${{ contains(github.ref, '-beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload extension
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: dist/
          
      - name: Notify on success
        if: success()
        run: |
          echo "Release ${{ github.ref_name }} created successfully!"
          echo "You can download it from the GitHub releases page."
          
      - name: Notify on failure
        if: failure()
        run: |
          echo "Failed to create release ${{ github.ref_name }}"
          echo "Please check the workflow logs for details." 